"""rebuild user

Revision ID: 95ad846c796e
Revises: 0fa3feeb530b
Create Date: 2016-12-28 12:09:06.367817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95ad846c796e'
down_revision = '0fa3feeb530b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('amount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'amount')
    # ### end Alembic commands ###
